---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medcure
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medcure
  template:
    metadata:
      labels:
        app: medcure
    spec:
      containers:
        - name: healthcare
          image: mowazzemali/star-agile-health-care:v1
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: medcure
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app:medcure
