---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Healthcare
  template:
    metadata:
      labels:
        app: Healthcare
    spec:
      containers:
        - name: Healthcare
          image: mowazzemali/star-agile-health-care:1
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: Healthcare
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: Healthcare
